[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xhelper"
version = "0.1.0"
dependencies = [
    "pandas",
    "pyreadstat",
]

[project.scripts]
xhelper = "xhelper.__main__:main"
